### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by HideBa** [reearth/reearth#102]
# Leader 
@issmail-basel 

# User story
When a lot of data is displayed on a map, it becomes difficult to see the data when viewed from a distance. The user wants to show how many data are in each region by clustering these data when viewed from a distance.

Here is the example.
![スクリーンショット 2021-08-26 16 08 10](https://user-images.githubusercontent.com/49897538/130917423-32a40b27-2663-4e1f-b362-ed4fec6df5bf.png)

# Requirements
* User can choose the style of marker
	* Color
	* Image
* User can choose which layers are clustered

# To-do
- Front end
    - [x] Use Cesium clustering feature
    - [x] Checkout Resium clustering feature
    - [x] Wrap Entities with CustomDataSource
    - [x]  Choose implementation details of CustomDataSource wrapper
    - [x] Add the ability to change color/image
    - [x] Add the ability to define sets of separate markers as cluster
    - [x] Discuss design options
    - [x] Define the suitable pixel rate/cluster size and/or make this optional
    - [ ] Work on UI
    - [ ] Link UI to clustering feature
    - [ ] Check which elements are more suitable to be modified and inform the backend
    - [ ] Discuss needed mutations/queries with backend
    - [ ] Add hooks to load/detect changes
    - [ ] Save changes of the clusters to backend (Add GraphQL mutations)
- Design
    - [x] Make Figma designs (options)
    - [x] Decide which design to adapt
    - [ ] Make changes as needed
- Back end
    - [ ] Discuss changes
    - [ ] Add queries and mutations to edit LayerGroup

# Test list

# FYI
https://cesium.com/learn/cesiumjs/ref-doc/EntityCluster.html

**Comment by HideBa** [comment]
Since we had released this feature, I close this PBL.
