### ISSUE TITLE
Clustering feature design

### ISSUE THREAD

**Issue by issmail-basel** [reearth/reearth#116]
# User story
When a lot of data is displayed on a map, it becomes difficult to see the data when viewed from a distance. The user wants to show how many data are in each region by clustering these data when viewed from a distance.

![スクリーンショット 2021-08-26 16 08 10](https://user-images.githubusercontent.com/49897538/130917423-32a40b27-2663-4e1f-b362-ed4fec6df5bf.png)

# Requirements
Add figma design which takes care of:
* User can choose the style of marker
	* Color
	* Image
* User can choose which layers are clustered

# To-do
- [ ] Make Figma designs (options)
- [ ] Decide which design to adapt
- [ ] Make changes as needed
