### ISSUE TITLE
Clustering feature front-end

### ISSUE THREAD

**Issue by issmail-basel** [reearth/reearth#117]
# User story
When a lot of data is displayed on a map, it becomes difficult to see the data when viewed from a distance. The user wants to show how many data are in each region by clustering these data when viewed from a distance.

![スクリーンショット 2021-08-26 16 08 10](https://user-images.githubusercontent.com/49897538/130917423-32a40b27-2663-4e1f-b362-ed4fec6df5bf.png)

# To-do
- [ ] Use Cesium clustering feature
- [ ] Checkout Resium clustering feature
- [ ] Wrap Entities with 
- [ ] Add the ability to change color/image
- [ ] Add the ability to define sets of separate markers as cluster
- [ ] Define the suitable pixel rate/cluster size and/or make this optional
- [ ] Discuss design options
- [ ] Work on UI
- [ ] Check which elements are more suitable to be modified and inform the backend
- [ ] Let backend know about needed mutations/queries
- [ ] Add hooks to load/detect changes
- [ ] Save changes of the clusters to backend
