### ISSUE TITLE
Property Migration

### ISSUE THREAD

**Issue by mimoham24** [reearth/reearth#13]
## Leader 
@rot1024 

Plug-ins can change their property schemas when they are updated. When you update a plugin, you can change the structure of existing properties to match the new schema, and you can also change the Without it, data would be lost, but that feature is not currently fully implemented.

## Acceptance criteria

| Should be                 | Newly install   | Upgrade to the same version                                                                                                                                                             | Upgrade to the diff version                                                                                                                                                             | Uninstall         |
|---------------------------|-----------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------|
| Layers / Widgets / Blocks | -               | If the extension is deleted, they should be deleted                                                                                                                                     | Plugin field should be replaced / If the extension is deleted, they should be deleted                                                                                                 | Should be deleted |
| Property                  | -               | Should be migrated (plugin field should be replaced) / If the extension is deleted, they should be deleted                                                                            | Should be migrated (plugin field should be replaced) / If the extension is deleted, they should be deleted                                                                            | Should be deleted |
| Property schemas          | Should be saved | If the extension is deleted, they should be deleted. Otherwise they should be recreated and saved. / If the plugin is scene-specific, the previous property schemas should be deleted | If the extension is deleted, they should be deleted. Otherwise they should be recreated and saved. / If the plugin is scene-specific, the previous property schemas should be deleted | Should be deleted |
| Plugin                    | Should be saved | Should be recreated and saved / If the plugin is scene-specific, the previous plugin should be deleted                                                                                | Should be recreated and saved / If the plugin is scene-specific, the previous plugin should be deleted                                                                                | Should be deleted |

## Completion condition

- [ ] All PRs were pass CI, code-reviewed and merged
- [ ] Tested on staging env
- [ ] Released in the production env
- [ ] A demonstration was held
