### ISSUE TITLE
front-end plugins feature

### ISSUE THREAD

**Issue by mimoham24** [reearth/reearth#18]
## Leader
@HideBa 

Currently, the system is designed to run each function as a plug-in, but it is not possible to install and use external plug-ins. By enabling the use of external plug-ins, it will be possible to proceed with development using resources other than internal resources, and users will be able to use more functions.

- Users can see a list of installable plug-ins.
- Users can install, update, and uninstall installable plugins.
- Developers can upload and use plugins that they are developing.
- You can install them by entering the GitHub link.
- Re:Earth automatically resolves inconsistencies caused by differences between the version of Re:Earth and the version of external plug-ins, allowing users to use plug-ins without worrying about version differences.
- Developers can include their plug-ins in the list by submitting a PR to have them included.
- Developers can publish the front-end part of their plug-ins so that Re:Earth can load it and run it as a Sandbox.

## Tasks

- [ ] Write document
- [x] Front-end
- [x] Back-end

### Completion condition

- [x] All PRs were passed CI, code-reviewed, and merged
- [x] Tested on staging env
- [x] Released in the production env
- [x] A demonstration was held
