### ISSUE TITLE
Improve infobox style

### ISSUE THREAD

**Issue by issmail-basel** [reearth/reearth#195]
## Leader
@mimoham24  

## User story
The user creates an infobox but can't set its position and style(padding, outline etc.), with this feature user can choose the place/alignment and style of infobox  on the screen. 

## Requirements
- Ability to change infobox position
  - Can choose infobox alignment (right - center - left) on the infobox panel
-  Ability to change infobox style
    - Can choose infobox width (small - middle - large) on the infobox panel
    - Can choose Height Type (Auto - Manual) on the infobox panel
    - Can choose infobox outline width on the infobox panel
    - Can choose infobox outline color on the infobox panel
- Ability to change infobox background mask on and off

## Examples
Center aligned, added padding and outline infobox:

Figma Link https://www.figma.com/file/bdnfDaGXGoNfUws4y7JItl/Re%3AEarth-UI-Gamma?node-id=9598%3A179736

## Development outline
- [ ] Decide which input type will be used for alignment and create custom if needed
- [ ] Add alignment option to manifest
- [ ] Implement alignment functionality/UI changes to infobox

## Testing List
- set infobox alignment
  - [ ] Right align the infobox
  - [ ] Left align the infobox
  - [ ] Center align the infobox
- [ ] set infobox width
- [ ] set infobox height manually
- [ ] set outline and can change width and color
- [ ] toggle on and off the infobox background mask
-  [ ]  open the editor and create an infobox
 - [ ] Preview the project and check the result
 - [ ] Publish project and check the result
