### ISSUE TITLE
[FE]: Stop using GraphQL to fetch merged property and merge properties and datasets in FE

### ISSUE THREAD

**Issue by HideBa** [reearth/reearth#229]
# Description
Front-end development task of #208 

## Todos
* [ ] Fetch data from REST API endpoint
* [ ] Merge properties and datasets on front-end
* [ ] Delete unused GQL code base
