### ISSUE TITLE
[BE]: Make username unique

### ISSUE THREAD

**Issue by HideBa** [reearth/reearth#244]
## Todos
- [ ] Add `CreateUniqueIndex` method to mongo layer
- [ ] Impl logic to validate if the same username has already existed to prevent duplicated username when user update username
- [ ] Prevent from using email address as username
