### ISSUE TITLE
Change layer's position by drag and drop

### ISSUE THREAD

**Issue by mimoham24** [reearth/reearth#36]
## Leader
@HideBa 

## User story
Currently, once you add a Layer, you can only change its position once you have changed its latitude and longitude from the Property window. In this case, the user needs to know the latitude and longitude. If not, the user has to get the latitude and longitude from Google Earth and enter it again from the Input field. By implementing this feature, the user can change the position of the layer by dragging and dropping, which makes it easier to adjust the layer.

## Requirements
* Can change the layer's position by drag and drop
* Can't drop outside of the canvas
* If the layer is linked to the dataset, it should overwrite the value by dragging and dropping
- [ ] write document
   - [ ] Front-end
   - [ ] Back-end

## Acceptance criteria

- 

## Completion condition

- [ ] All PRs were passed CI, code-reviewed, and merged
- [ ] Tested on staging env
- [ ] Released in the production env
- [ ] A demonstration was held
