### ISSUE TITLE
Tag system(Basic)

### ISSUE THREAD

**Issue by mimoham24** [reearth/reearth#43]
## Leader
@HideBa 
## User story
Users want to switch the contents on the map by attributes. For example, They want to switch the display of contents on the map by any attribute such as "nature/animals," "buildings," "traditional events," "OO town," "OO village," or "Edo period," "Meiji period," etc.

## Requirements
- Ability to add arbitrary tags to layers
    - Create tags from the layer's property window
    - Attach tags on each layer
    - Detach tags from each layer
    - Can't delete tags from layer's property window
    - Create tag groups
    - When adding linked layers
        - Create tags that don't exist(internally)
        - Attach tags to each layer
- Manage tags from `tag manager`
	- Inside the scene properties, `tag manager` should exist
	- From tag manager users can create tags and tag groups
	- Tags and tag groups can be deleted except the `default` tag group only when they don't have any tags inside.
- Tag cloud widget
	- Activate widget
	- All existing tags should be shown
	- User can choose the text color, select color, and the bg color of the widget.
	- By clicking the tags inside of the tag cloud widget, the layers and storytelling should be filtered by them.
## Examples
<img width="975" alt="スクリーンショット 2021-04-28 13 20 55" src="https://user-images.githubusercontent.com/49897538/116346164-a70f0300-a824-11eb-8dca-42da666f6eaa.png">

<img width="951" alt="スクリーンショット 2021-04-28 13 21 59" src="https://user-images.githubusercontent.com/49897538/116346199-bc842d00-a824-11eb-9757-c085fd606c3d.png">

## Testing list
- [ ] Editor
	- [ ] Tag manager
		- [ ] When tag manager is selected
			- [ ] Tag manager properties are shown on right panel
			- [ ] Tag manager has "Default" tag group as default
			- [ ] "Default" tag group cannot be deleted
			- [ ] "Defaut" tag group doesn't have "x" button
			- [ ] All tag groups which belongs to the scene are show
			- [ ] All tag groups has bin icon button except "Default" tag group
			- [ ] All tag groups has input area
			- [ ] At the most buttom of Tag manager properties, Input area is shown to create a tag group
			- [ ] If user input "hello", tag can be created with "hello" label inside of the tag group
			- [ ] Tag has delete button
			- [ ] When delete button of the tag whose label is "hello" clicked
				- [ ] Tag is deleted
				- [ ] Tag should be detached from all layers which the tag originally attached
				- [ ] If user input "hello" user can create the tag whose label is "hello" again
			- [ ] When user input text, the existing tags are not shown(There is no feature to attach tag to something)
			- [ ] When user click delete button of the tag group(label is "year", tags are "1990", "2000", "2010")
				- [ ] All tags(whose label are "1990", "2000", "2010") which belong to the tag group (label is "year") are deleted
				- [ ] All tags(whose label is "1990", "2000", "2010") are detached from all layers
			- [ ] Same labeled tag group cannot be created
			- [ ] Same labeled tag cannot be created under the same tag group
	- [ ] Layer
		Case:
		- Scene has two tag groups
			- "Year" This tag group has 
				- "1990"
				- "2000"
				- 2010"
			- "Place"
				- "Japan"
				- "China"
				- "Canada"
				- "Syria"
		- [ ] When the layer is selected
			- [ ] Right window has "Tags" tab with tag icon
			- [ ] Tag tab has "Default" tag group
			- [ ] "Default" tag group cannot be detached from any layers
			- [ ] When user focus on input area inside of "Year" tag group
				- [ ] "1990", "2000", "2010" tags are show
				- [ ] "Japan", "China", "Canada", "Syria" are not shown
				- [ ] When user hover the tag, its color changes
				- [ ] Tags are clickable
				- [ ] When user input "20"
					- [ ] "2000" and "2010" are shown
					- [ ] "1990" are not shown
				- [ ] When user click "1990" tag inside of pull-down list
					- [ ] "1990" tag is attached on the layer
					- [ ] "1990" tag is shown inside of "Year" tag group with "x" icon
				- [ ] When user click "x" button of "1990" tag
					- [ ] "1990" tag is detached from the layer
				- [ ] When user click "x" button of "Year" tag group
					- [ ] "Year" tag group is detached from the layer
					- [ ] "1990", "2000", "2010" tags are detached from the layer
			- [ ] When user blur on input area
				- [ ] Pull down collapse
	- [ ] Layer group
		Case: same as an above layer test case
		- [ ] Same test as an above layer test
		- [ ] When the layer group has "Year" tag group
			- [ ] All children have "Year" tag group
			- [ ] When the layer group has "1990" tag
				- [ ] All children have "1990" tag inside of "Year" tag group
				- [ ] Children cannot detached "1990" from own tag properties
				- [ ] Layer group can detatch "1990" tag by clicking "x" button
				- [ ] When the child adds "2000" tag
					- [ ] The child has "1990" and "2000" tag
					- [ ] Other children only has "1990" tag unless they has own tag which has been added manually
					- [ ]

**Comment by HideBa** [comment]
Since we had released this feature, I close this PBL.
